version: '3.8'

networks:
  internal:

services:
  db:
    image: postgres
    container_name: swift-server-ajm-postgres
    networks:
      - internal
    restart: always
    env_file:
      - .env
  web:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: swift-server-ajm-web
    networks:
      - internal
    ports:
      - "3002:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
