version: '3.8'

networks:
  internal:

services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: swift-server-ajm-web
    networks:
      - internal
    ports:
      - "80:3002"
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    container_name: swift-server-ajm-postgres
    networks:
      - internal
    restart: always
    ports:
      - "5432:5432"

