version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zoomapp
  app:
    environment:
      - DB_NAME=zoomapp
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "80:3002"
    build:
      docker:
        release:
          dockerfile: Dockerfile
          target: builder
        web: Dockerfile
    run:
      web: docker-compose up
